# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  secret_key_base: 9caf11127d8c4b1052f2592576be385ffa1172334c581ccab4c817ebbf0a58636fb8f8f4a578a4441fad6580fc8267e61b3cb48021f8f565ca5cdeff9db19663

test:
  secret_key_base: 27dea7d7fbefb7e76e8f38ca09f5691e23f5753f9830157dbfd6ab9c0e5e5aa5d3a0aac62ac7a55f66567b035710696814acdd6bd5050741ea40a7c5cbaea7d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
